name: Cypress Tests

on:
  push:
    branches:
      - main
      - develop
      - VikashAutomation

  pull_request:
    branches:
      - main
      - develop
      - VikashAutomation

jobs:
  cypress-run:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        run: npm test

      - name: Send Email Notification
        if: always()
        uses: dawidd6/action-send-mail@v6
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_APP_PASSWORD }}
          subject: Cypress Test Result - ${{ job.status }}
          to: ${{ secrets.EMAIL_TO }}
          from: ${{ secrets.EMAIL_USERNAME }}
          body: |
            Cypress Test Execution Completed

            Repository: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            Workflow: ${{ github.workflow }}
            Status: ${{ job.status }}

            Commit:
            ${{ github.sha }}

            View workflow:
            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}